// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports, module) {
    var $;
    $ = require('jquery');
    $.notification = function(options) {
      var div, notifications, settings;
      settings = {
        type: 'info',
        msg: 'info',
        time: 3,
        fixed: false
      };
      settings = $.extend(settings, options);
      notifications = {
        'success': 'alert-success',
        'info': 'alert-info',
        'warning': 'alert-warning',
        'error': 'alert-danger'
      };
      div = ($('<DIV/>')).css({
        display: 'none',
        'z-index': 1040
      }).attr({
        'data-type': 'notification'
      }).addClass('alert fade in ' + notifications[settings.type]);
      div.attr({
        'id': new Date().getTime()
      });
      if (settings.fixed) {
        div.css({
          position: 'fixed',
          top: '0px',
          left: '0px',
          right: '0px'
        });
      }
      div.append(($('<A/>')).addClass('close').attr({
        'data-dismiss': 'alert'
      }).text('×'));
      div.append(($('<CENTER/>')).append(($('<STRONG/>')).text(settings.msg)));
      if (($('BODY DIV[data-type="notification"]')).length) {
        ($('BODY DIV[data-type="notification"]')).remove();
      }
      ($('BODY')).prepend(div);
      div.slideDown(600);
      return setTimeout(function() {
        return div.slideUp(function() {
          div.remove();
          return div = null;
        });
      }, settings.time * 600);
    };
    return void 0;
  });

}).call(this);
